# Site settings
title: "XLsn0w"
email: xlsn00w@gmail.com
description: "XLsn0wBlog"
baseurl: ""
url: "https://xlsn0w.github.io"
title_description: "iPhone  Hacker"
title_image: "https://github.com/XLsn0w/XLsn0w.github.io/blob/master/XLsn0w.png?raw=true"
google_analytics: "UA-20365477-4"
disqus_account:
github_repository: https://github.com/XLsn0w/XLsn0w.github.io
addthis_id:
post_limit:

# Social usernames/URLs
github_username:  XLsn0w
twitter_username: XLsn0w
instagram_username: xlsn0w
reddit_username: 
linkedin_link:
google_plus_link: https://plus.google.com/118148947586555888325
stackoverflow_link: https://stackoverflow.com/users/6675871/xlsn0w
xing_link:
facebook_link:

# Footer
footer_left: "关注 <i class=\"fa fa-heart\"></i> <a href=\"http://www.jianshu.com/u/eacc1a5d2fda\">XLsn0w's 简书</a>"
footer_right: "Follow <a href=\"https://github.com/XLsn0w\">XLsn0w's Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
